### ISSUE TITLE
Saying that GET should have no side effects is glossing over what is happening

### ISSUE THREAD

**Issue by hurricane766** [pillarjs/understanding-csrf#12]
I think you're assuming that the information available is trivial and unimportant. Someone other than the authorized user is getting that data and private information could then be used to execute other types of attacks.

For example, I may not be able to directly transfer money from your account using a POST request, but I can GET all your banking information and then try and use that in other ways.

**Comment by sant0shg** [comment]
The attacker does not run the attack on her machine, and she will not know the response the user gets.
As the OWASP[ guide states here](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF))

> CSRF attacks target functionality that causes a state change on the server, such as changing the victim's email address or password, or purchasing something. Forcing the victim to retrieve data doesn't benefit an attacker because the attacker doesn't receive the response, the victim does. As such, CSRF attacks target state-changing requests.

So the guide states that there should not be any side effects with a GET request. 

> Make sure that none of your GET requests change any relevant data in your database. This is a very novice mistake to make and makes your app susceptible to more than just CSRF attacks.

**Comment by hurricane766** [comment]
Ok, that make sense now, thanks :)
