### ISSUE TITLE
Older browser clause

### ISSUE THREAD

**Issue by bitinn** [pillarjs/understanding-csrf#2]
`But for older browsers, this is pretty simple as long as the attack knows where to get a CSRF token.`

Assuming the token is correctly implemented (per user session), how can an attacker obtain such CSRF token?

It seems to suggest older browsers are still vulnerable to CSRF attacks even when CSRF tokens are correctly used. I am not sure if that's the case.

**Comment by jonathanong** [comment]
they can GET a page, parse the HTML (assuming they know where to get it), and get the token. 

but newer browsers have CORS, so they wouldn't be able to POST with or without a CSRF token.

**Comment by dougwilson** [comment]
And by "older browsers" we are now talking years and years ago (before Chrome even existed).

**Comment by bitinn** [comment]
Older IE doesn't support cross-origin ajax and block cookie from iframe, right? I don't believe there is a way for attacker to GET `/csrf` from another site?

**Comment by dougwilson** [comment]
All you need is IE 5.5 or IE 6: http://www.securityfocus.com/bid/3721/discuss

**Comment by dougwilson** [comment]
Those browsers were EOL'd before the issue was found and now lives on un-patched forever.

**Comment by bitinn** [comment]
@dougwilson Ah thx I saw that too while researching this topic.

I guess browsers that breach same-origin policy are always going to be vulnerable to CSRF, maybe add this link as an example?

Either way, I just don't want ppl to incorrectly assume that `a browser without CORS support` equals `a browser doesn't respect same-origin policy` :)

**Comment by dougwilson** [comment]
Gotcha. Yes, since CORS is a double-opt-in protocol, both the web browser and the server need to be aware and support CORS in order for you to read cross-origin via CORS. It's probably also important to note that the "same origin" concept has exists for almost as long as JavaScript on the web, though "same origin" as we define it today was never nailed down until December 2011 with RFC 6454 (and thus the meaning of "same origin" doesn't mean anything in particular before then).

**Comment by bitinn** [comment]
@dougwilson Related question: even when targeting modern browsers alone, can we actually avoid csrf token completely? like the doc says `CSRF tokens will eventually be unnecessary`.

For example, isn't POST from HTML form not in the sam-origin policy protection? Without csrf token we at least need to do additional checks on `referrer`. And referrer can be hidden by `no-referrer` meta and through things like HTTPS -> HTTP requests.

**Comment by dougwilson** [comment]
> For example, isn't POST from HTML form not in the sam-origin policy protection? 

No, `<form` can always be cross-origin.

> Without csrf token we at least need to do additional checks on referrer. 

Many privacy software removes this header, so it's useless to check this. Also, most browsers will leave it blank for a cross-origin request, so it's useless if you want your site to work with everyone.

**Comment by bitinn** [comment]
This section suggest CSRF tokens are going away https://github.com/pillarjs/understanding-csrf#csrf-tokens-will-eventually-be-unnecessary, but both of your answers seem to imply there are no better ways than CSRF tokens?

An attacker can construct a simple HTML form that post to target site, without CSRF token, how can a modern browser prevent this attack?

I must be confusing something here.

**Comment by dougwilson** [comment]
Just don't accept non-JSON bodies and you're good to go. @jonathanong would have to ellaborate more on that section.

**Comment by jonathanong** [comment]
yup. i'll update

**Comment by bitinn** [comment]
@jonathanong Cheers! I thought checking `Origin` header might also be a valid approach for modern browsers protection, but the need for CSRF token seem huge as of now (I can't find a popular framework without it).
