### ISSUE TITLE
Improper use of "idempotent"

### ISSUE THREAD

**Issue by marfire** [pillarjs/understanding-csrf#5]
One of your headings reads _GET is always idempotent_. Although that is certainly good practice in general, it doesn't have anything to do with CSRF. A GET request that deleted data would be idempotent, but still a major CSRF vulnerability.

I suggest _GET should not have side effects_, or something like that.

**Comment by marfire** [comment]
Here's the reference I was looking for: http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html. 

What matters here is _safety_, not _idempotence_.

**Comment by dougwilson** [comment]
Correct, there are two types of methods: impotent and safe. The CSRF docs should reference safe, rather than impotent.
