### ISSUE TITLE
Get the CSRF through simulated client

### ISSUE THREAD

**Issue by idf** [pillarjs/understanding-csrf#7]
The document says "An attacker would have to somehow get the CSRF token from your site, and they would have to use JavaScript to do so." But if the attacker uses other scripting language like Python rather than client-side JavaScript, she can get the CSRF token by programmatically simulating client `GET`/`POST` to get the CSRF token like this [link](http://stackoverflow.com/questions/13567507/passing-csrftoken-with-python-requests). CORS does not prohibit such behaviour. 

In this case, how to avoid attackers getting the CSRF tokens if the website has some `POST` through form.

**Comment by jonathanong** [comment]
CSRF tokens are usually cookie/session based, so the simulated client would need that information to do any damage. if the client has the cookie/session, then CSRF is the least of the problem.

**Comment by idf** [comment]
If the simulated client has the cookie/session, how to prohibit its malbehavior?

**Comment by xehpuk** [comment]
Invalidate the session and teach your users not to give away their cookies.

**Comment by idf** [comment]
Thanks for the answers!
